apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-auth
stringData:
{{- if eq .Values.environment "azure" }}
  GF_AUTH_AZUREAD_CLIENT_ID: "{{ .Values.grafana.azure.ad.clientId }}"
  GF_AUTH_AZUREAD_CLIENT_SECRET: "{{ .Values.grafana.azure.ad.clientSecret }}"
{{- else }}
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
{{- end }}
